name:
  hertz.demo
port:
  8084

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  dbname: hertz_demo
  max_open_conns: 200
  max_idle_conns: 50


redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
  pool_size: 100
